# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(949, 555)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_background = QtWidgets.QLabel(self.centralwidget)
        self.label_background.setGeometry(QtCore.QRect(60, 50, 341, 451))
        self.label_background.setStyleSheet("border-image: url(:/image/image/bessel.jpg);\n"
                                            "border-top-left-radius: 30px;\n"
                                            "border-bottom-left-radius: 30px;")
        self.label_background.setText("")
        self.label_background.setObjectName("label_background")
        self.label_backgroundr = QtWidgets.QLabel(self.centralwidget)
        self.label_backgroundr.setGeometry(QtCore.QRect(400, 50, 441, 451))
        self.label_backgroundr.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                             "border-top-right-radius: 30px;\n"
                                             "border-bottom-right-radius: 30px;")
        self.label_backgroundr.setText("")
        self.label_backgroundr.setObjectName("label_backgroundr")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(690, 60, 111, 41))
        self.frame.setStyleSheet("QPushButton {\n"
                                 "    border:none;\n"
                                 "}\n"
                                 "QPushButton:hover{\n"
                                 "    padding-bottom: 5px;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_minimize = QtWidgets.QPushButton(self.frame)
        self.pushButton_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_minimize.setIcon(icon)
        self.pushButton_minimize.setObjectName("pushButton_minimize")
        self.horizontalLayout.addWidget(self.pushButton_minimize)
        self.pushButton_close = QtWidgets.QPushButton(self.frame)
        self.pushButton_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon1)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        self.frame_func = QtWidgets.QFrame(self.centralwidget)
        self.frame_func.setGeometry(QtCore.QRect(540, 190, 171, 221))
        self.frame_func.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_func.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_func.setObjectName("frame_func")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_func)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PushButton_1 = QtWidgets.QPushButton(self.frame_func)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButton_1.sizePolicy().hasHeightForWidth())
        self.PushButton_1.setSizePolicy(sizePolicy)
        self.PushButton_1.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PushButton_1.setFont(font)
        self.PushButton_1.setStyleSheet("#PushButton_1{\n"
                                        "    border:3px solid;\n"
                                        "    border-radius:15px;\n"
                                        "    background-color:rgb(255,255,255)\n"
                                        "}\n"
                                        "#PushButton_1:hover{\n"
                                        "    background-color:rgb(242,129,17)\n"
                                        "}\n"
                                        "")
        self.PushButton_1.setObjectName("PushButton_1")
        self.verticalLayout.addWidget(self.PushButton_1)
        self.PushButton_2 = QtWidgets.QPushButton(self.frame_func)
        self.PushButton_2.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PushButton_2.setFont(font)
        self.PushButton_2.setStyleSheet("#PushButton_2{\n"
                                        "    border:3px solid;\n"
                                        "    border-radius:15px\n"
                                        "}\n"
                                        "#PushButton_2:hover{\n"
                                        "    background-color:rgb(242,129,17)\n"
                                        "}\n"
                                        "")
        self.PushButton_2.setObjectName("PushButton_2")
        self.verticalLayout.addWidget(self.PushButton_2)
        self.label_tips = QtWidgets.QLabel(self.centralwidget)
        self.label_tips.setGeometry(QtCore.QRect(470, 440, 321, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_tips.setFont(font)
        self.label_tips.setStyleSheet("color:red")
        self.label_tips.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tips.setObjectName("label_tips")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(470, 130, 311, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(720, 210, 91, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(20, 20))
        self.lineEdit.setStyleSheet("#lineEdit{\n"
                                    "    border:3px solid;\n"
                                    "    border-radius:5px;\n"
                                    "    background-color:rgb(255,255,255)\n"
                                    "}\n"
                                    "\n"
                                    "")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_backgroundr.raise_()
        self.label_background.raise_()
        self.frame.raise_()
        self.frame_func.raise_()
        self.label_tips.raise_()
        self.label_title.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_minimize.clicked.connect(MainWindow.showMinimized)
        self.pushButton_close.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PushButton_1.setText(_translate("MainWindow", "B样条曲线"))
        self.PushButton_2.setText(_translate("MainWindow", "贝塞尔曲线"))
        self.label_tips.setText(_translate("MainWindow", "第六组 2022.10.23"))
        self.label_title.setText(_translate("MainWindow", "B样条曲线和贝塞尔曲线"))
        self.lineEdit.setText(_translate("MainWindow", "3"))
        self.label.setText(_translate("MainWindow", "次"))


import res_rc
